version: '3'
services:

  graylog:
    image: graylog/graylog:3.3
    volumes:
      - /root/docker/graylog/data/:/usr/share/graylog/data/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_ROOT_USERNAME=admin
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      # echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_PUBLISH_URI=http://graylog.gs.com/
    networks:
      - common-all
      - database-common
      - nginx-common  


networks:
  database-common:
    external: true
  common-all:
    external: true
  nginx-common:
    external: true
    

